name: ${STACK_NAME:-ligolo-ng-aio}

x-build-args: &x-build-args
  WEBUI_REF: "${WEBUI_REF:-master}"
  LIGOLO_VERSION: "${LIGOLO_VERSION:-latest}"
  # VITE_API_URL: "http://127.0.0.1:${WEBUI_PORT:-8000}"

x-service-base: &x-service-base
  env_file:
    - .env
  # environment:
  #   LIGOLO_ARGS: "${LIGOLO_ARGS:-selfcert}"
  #   LIGOLO_VERSION: "${LIGOLO_VERSION:-latest}"
  tty: true
  stdin_open: true
  ## Include your own runtime configs.
  # volumes:
  #   - ./config/ligolo-ng.yaml:/opt/ligolo-ng/ligolo-ng.yaml
  #   - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun:/dev/net/tun
  container_name: "${CONTAINER_NAME:-${STACK_NAME:-ligolo-ng-aio}}"
  restart: unless-stopped

x-service-cli: &x-service-cli
  image: "ligolo-aio-cli:${IMAGE_TAG:-${LIGOLO_VERSION:-latest}}"
  <<: *x-service-base
  build:
    context: ./build
    target: cli
    args:
      <<: *x-build-args

x-service-full: &x-service-full
  image: "ligolo-aio-full:${IMAGE_TAG:-${LIGOLO_VERSION:-latest}}"
  <<: *x-service-base
  build:
    context: ./build
    target: full
    args:
      <<: *x-build-args
  healthcheck:
    test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/ >/dev/null || exit 1"]
    interval: 30s
    timeout: 5s
    start_period: 15s
    retries: 5

services:
  ligolo-ng-full-bridge:
    <<: *x-service-full
    ports:
        - "${WEBUI_HOST:-127.0.0.1}:${WEBUI_PORT:-8000}:${WEBUI_PORT_MAP:-8000}"
        - "${AGENT_HOST:-0.0.0.0}:${AGENT_PORT:-11601}:${AGENT_PORT_MAP:-11601}"
    networks:
        - ligolo-net
    container_name: "${CONTAINER_NAME:-${STACK_NAME:-ligolo-aio}}-full"
    profiles: ["full-bridge"]

  ligolo-ng-cli-bridge:
    <<: *x-service-cli
    ports:
      - "${AGENT_HOST:-0.0.0.0}:${AGENT_PORT:-11601}:${AGENT_PORT_MAP:-11601}"
    networks:
      - ligolo-net
    container_name: "${CONTAINER_NAME:-${STACK_NAME:-ligolo-aio}}-cli"
    profiles: ["cli-bridge"]

  ligolo-ng-full-host:
    <<: *x-service-full
    network_mode: host
    container_name: "${CONTAINER_NAME:-${STACK_NAME:-ligolo-aio}}-full-host"
    profiles: ["full-host"]

  ligolo-ng-cli-host:
    <<: *x-service-cli
    network_mode: host
    container_name: "${CONTAINER_NAME:-${STACK_NAME:-ligolo-aio}}-cli-host"
    profiles: ["cli-host"]
    

networks:
  ligolo-net:
    name: "${CONTAINER_NAME:-${STACK_NAME:-ligolo-aio}}-net"
    driver: bridge
    ipam:
      driver: default
      config:
        # NOTE: We are using CGNAT range for the ligolo container to avoid potential IP conflicts with target environments
        - subnet: 100.96.10.0/24
          gateway: 100.96.10.1